version: '3.7'

services:
  web:
    image: ziralink.web
    container_name: ziralink-web
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - "4000:80"
      - "4001:443"